networks:
  task-tracker-net:
    driver: bridge
services:
  app:
    container_name: task-tracker
    build:
      context: .
      dockerfile: /TaskTracker.API/Dockerfile
    ports: 
      - "8080:8080"
    networks:
      - task-tracker-net
    depends_on: 
      postgres_db:
        condition: service_healthy
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
  postgres_db:
    container_name: postgres    
    image: postgres:17.6
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: task-tracker
    ports:
      - "5432:5432"
    networks: 
      - task-tracker-net   
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5
volumes:
  postgres-data:

    
         
  
  